export const HOME_BUTTON_CLICKED = 'HOME_BUTTON_CLICKED';
export const SETTING_BUTTON_CLICKED = 'SETTING_BUTTON_CLICKED';
export const PROFILE_BUTTON_CLICKED = 'PROFILE_BUTTON_CLICKED';
export const NOTIFICATION_BUTTON_CLICKED = 'NOTIFICATION_BUTTON_CLICKED';
